#!/bin/bash
    batt=$(cat /sys/class/power_supply/BAT0/capacity)
    
    if [ "$batt" -le 25 ]; then
        echo -e "  $batt%"
    elif [ "$batt" -gt 25 ] && [ "$batt" -lt 50 ]; then
        echo -e "  $batt%"
    elif [ "$batt" -ge 50 ] && [ "$batt" -le 75 ]; then
        echo -e "  $batt%"
    elif [ "$batt" -gt 75 ] && [ "$batt" -lt 100 ]; then
        echo -e "  $batt%"
    elif [ "$batt" -eq 100 ]; then
        echo -e "  $batt%"
    fi
