#!/bin/bash

batt=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

# Battery icons array
battery_icons=("" "" "" "" "")

charging_icon=""
if [ "$status" = "Charging" ]; then
    charging_icon=" "  # This is a lightning bolt symbol with a preceding space
fi

# Determine index for battery icon array
index=$((batt / 25))
if [ "$index" -gt 4 ]; then
    index=4
fi

icon="${battery_icons[$index]}"

echo -e "$icon  $batt%$charging_icon"
